# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.softwarefly.net
date_format: "ordinal"
title: Jfly
subtitle: "打码改变人生"
description: "SoftwareFly的个人博客"
keywords: softwarefly, jfruan
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: SoftwareFly
organization: XJTU
organization_url: http://www.xjtu.edu.cn
github_username: softwarefly
location: Xi'an, China
email: xjtu.jfruan@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: softwarefly/softwarefly.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 

# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: softwarefly
#    repo: blog-comments
#    oauth:
#        client_id: 98e5eb81d1e8db610889
#        client_secret: 2c5d5f1a767abb81764d6b296f789c9e15c4e7cd

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: softwarefly
    repo: blog-comments
    clientID: 98e5eb81d1e8db610889
    clientSecret: 2c5d5f1a767abb81764d6b296f789c9e15c4e7cd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-127576329-1
